### ISSUE TITLE
Current ToDo's

### ISSUE THREAD

**Issue by JKetelaar** [JKetelaar/PHP-FUT-API#2]
We currently have a few things to be done, so feel free to contribute:  
- [x] Fix the [Hasher](https://github.com/JKetelaar/PHP-FUT-Bot/blob/master/src/JKetelaar/fut/bot/user/Hasher.php)
- [ ] Remove TOTP requirement
- [x] Create a proper Composer project from this (so `composer require jketelaar/php-fut-bot` can be used)
